### ISSUE TITLE
Cosmetic filters are not supported by bromite

### ISSUE THREAD

**Issue by PurpleCodingWizard** [xarantolus/filtrite#6]
Hi, I just wanted to let you know. That bromite's filter engine doesn't support cosmetic filtering. You can verify by going to some of the cookie websites and notice the pop-ups still show. 

Example: huawei.com still shows a cookie banner even when you use the bromite-extended filter which has this list's filter in it: 
https://secure.fanboy.co.nz/fanboy-cookiemonster.txt which you use.

It would be better to remove them as they do not server any use

**Comment by xarantolus** [comment]
I think you are mostly right about this, but there might still be some benefits. The list for example contains `wsj.com###cx-notification` and when I open [WSJ](https://www.wsj.com/) in Bromite, no cookie banner appears (compared to Chromium without adblock, where it does). However, it could be that this blocking comes from another list, not 100% sure.

When running the tool with only this list, the log is the following:

```
[0917/075725.252269:ERROR:rule_stream.cc(88)] (error:106) Unknown URL rule option:
bethesda.net#?#visor-alert[name="visor-alert"] > div[class=""] > div > div:last-child:-abp-has( > a[href$="/cookie-policy"])
                                                                                                         ^

[0917/075725.252891:ERROR:rule_stream.cc(88)] (error:23) Unknown URL rule option:
podleze-piekielko.pl#$#abort-on-property-read cookieman
                      ^
```

So the ruleset converter tool understands all except for two rules from the list. I'm not 100% sure how bromite applies the rules (e.g. it could be possible that they are added to the ruleset file, but then bromite doesn't understand some rules; however I didn't find the exact matching logic in the [AdBlock patch](https://github.com/bromite/bromite/blob/master/build/patches/Bromite-AdBlockUpdaterService.patch) so I can't really check that), but in general it seems like *some* rules from the list should work (except for cosmetic filters), which is why I would keep it.

**Comment by xarantolus** [comment]
BTW I have since created [two user scripts](https://github.com/xarantolus/bromite-userscripts) that also block these kinds of popups, so I'll close this
